---
- name: Include stuff
  include_vars: vars/vars.yml

- name: Add Docker test repo
  yum_repository: name=docker-test.repo description='Docker test repo' baseurl=https://yum.dockerproject.org/repo/testing/centos/7 enabled=yes gpgcheck=yes gpgkey=https://yum.dockerproject.org/gpg

- name: Install Docker
  yum: name=docker-engine-1.12.0-0.4.rc4.el7.centos state=present

- name: Start Docker service
  service: name=docker state=started enabled=yes

- name: ensure that pip is installed
  shell: curl -s https://bootstrap.pypa.io/get-pip.py | python -
         creates=/usr/bin/pip

- name: ensure that docker-py client library has been installed via pip
  pip:
    name: docker-py
    state: latest

- name: Initialize the swarm
  shell: docker swarm init --secret {{ docker_swarm_secret }}
  ignore_errors: yes
  when: docker_role == 'manager'

- name: Join the swarm
  shell: docker swarm join --secret {{ docker_swarm_secret }} 10.1.43.2:2377 #Need to make this IP dynamic
  ignore_errors: yes
  when: docker_role == 'worker'
